- name: Set home directory variable
  set_fact:
    home_dir: "{{ ansible_env.HOME }}"

- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Change default shell to ZSH
  ansible.builtin.shell: chsh -s $(which zsh)
  become: true
  args:
    executable: /bin/bash

- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Install syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Copy zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ home_dir }}/.zshrc"
    mode: '0644'

- name: Copy p10k.zsh
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "{{ home_dir }}/.p10k.zsh"
    mode: '0644'

# - name: Source zshrc
#   ansible.builtin.command: source "{{ home_dir }}/.zshrc"
#   args:
#     executable: /bin/zsh

